feat: New developer page
proxify-ab/docs pull request #1
Opened 2024-08-20 14:11 UTC by TamaraZoric

## Description of Problem
The Vue site needs to expand by introducing a "Developers" section to showcase certified developers, allowing users to contact and hire them through a partner. However, the current structure only accommodates "Partners," and there isn’t a clear way to incorporate this new section without complicating the navigation and potentially disrupting the site’s design consistency.

The challenge is to integrate this new section without cluttering the navigation and to ensure a consistent design and maintainable code structure across both the "Partners" and "Developers" sections.

## Proposed Solution
1. Navigation Update:
	- Merge "Partners" and "Developers" under a single "Experts" navigation item.
2. Reusable Components:
	- Propose new reusable components that introduce wrappers and shared CSS and logic for both "Partners" and "Developers" sections.
	- Refactor the "Partners" section by extracting reusable code without changing the existing UI/UX.
3. Developers Pages:
	- Create a new /developers page to list all Vue-certified developers.
	- Develop individual developer detail pages under /developers/{developerSlug}.
4. Partners Page Enhancements:
	- Add "Proxify" as a new partner.
	- Implement a conditional Contact button that either opens an email or redirects to a contact form based on configuration. Expand the Partner interface to support these updates.
5. Configuration & Utilities:
	- Centralize developer data management with new configuration files.
	- Add utility functions for UTM tracking and profile image handling.

## Additional Information
Additional information about implementation will be added in this file
https://docs.google.com/document/d/1TCQDRCPSBeDQuyH7ENWdIu0Dabu4KuypTA2VQrzQ0bY/edit

2024-08-23 07:26 UTC, borna9II requested changes

2024-08-23 07:26 UTC, borna9II commented on .vitepress/theme/components/CallToActionSection.vue
> +    showDivider?: boolean
Are semicolons extra? I've checked other files and there they are omitted.

2024-08-23 07:26 UTC, borna9II commented on .vitepress/theme/components/CardList.vue
> +    splitBy: 'platinum'
Check semicolon and colon consistency

2024-08-23 07:26 UTC, borna9II commented on .vitepress/theme/components/CardList.vue
> +    ;[array[i], array[j]] = [array[j], array[i]]
Is a semicolon at the start needed?

great refactoring of their function!

2024-08-23 07:26 UTC, borna9II commented on .vitepress/theme/components/PageShowcaseListLayout.vue
> +}>()
Semicolons

2024-08-23 07:26 UTC, borna9II commented on src/developers/components/DeveloperExperiences.vue
> +            <p v-if="desc.type === 'p'">{{ desc.content }}</p>
Isn't better that desc.type is desc.isParagraph (bool vs string)?

2024-08-23 07:26 UTC, borna9II commented on src/developers/components/type.ts
> +  content: string[];
It would be better that instead of type string, we have a bool as it used only for boolean operation

2024-08-23 07:26 UTC, borna9II commented on src/developers/partnerConfig.js
> +  },
The use of commas should be consistent in all files

2024-08-23 08:03 UTC, dionvogliqi commented on src/partners/components/PartnerHero.vue
> +    <template #lead>
I see we got rid of title and lead classes, but styles are written for those classes. 
Could this break anything on their side?

2024-08-23 08:03 UTC, dionvogliqi commented on src/partners/components/PartnerPage.vue
> +      <p v-for="desc in description" :key="desc" v-html="desc"></p>
Can we have index as key for this item? I'm not sure about what description contains, but could it be that it has duplicate values?

2024-08-23 11:24 UTC, TamaraZoric commented on src/developers/components/type.ts
> +  content: string[];
I like idea, but I will use something more generic. I think "isGrouped" is more generic not indicating which html element we will use, but if it is something that has items or something that is singe item.

2024-08-23 11:24 UTC, TamaraZoric commented on src/developers/components/DeveloperExperiences.vue
> +            <p v-if="desc.type === 'p'">{{ desc.content }}</p>
Updated based on change in type.ts file

2024-08-23 11:28 UTC, TamaraZoric commented on .vitepress/theme/components/CallToActionSection.vue
> +    showDivider?: boolean
In general, semicolons are optional thing. Since in most existing files they do not use it, I will remove it from vue props.

2024-08-23 11:47 UTC, TamaraZoric commented on .vitepress/theme/components/CardList.vue
> +    ;[array[i], array[j]] = [array[j], array[i]]
As for the semicolon as the first character in the line, I could not find what I mentioned to you earlier today, but I found this:

"This function is a standard implementation of the Fisher-Yates (or Knuth) shuffle algorithm. It efficiently shuffles the array in place, ensuring a random distribution of the elements. The semicolon ; before the destructuring assignment ensures that this line is correctly interpreted after the Math.floor expression, which is important in JavaScript where automatic semicolon insertion can cause issues in certain cases."

In general, this project does not have implemented standard for having `;` in the end of line. In case we add it in the end of line 49, it may be removed by someone who has rule to remove all `;` from end of lines. If that happens, JS will interprete this line as `const j = Math.floor(Math.random() * (i + 1))[array[i], array[j]] = [array[j], array[i]]` and create bug. 
We have 2 options here: 
1. leave it at the end of line `const j = Math.floor(Math.random() * (i + 1));` and risk that someone may remove it automatically or with some linter rules.
2. leave it in the beginning `;[array[i], array[j]] = [array[j], array[i]]` and have "strange" code

What do you think, what is more clean?

2024-08-23 11:56 UTC, TamaraZoric commented on src/developers/partnerConfig.js
> +  },
Checked, it seems correct for JS file.

2024-08-23 11:59 UTC, TamaraZoric commented on src/partners/components/PartnerHero.vue
> +    <template #lead>
I actually moved their code in reusable `PageHero` component. Since style was `scoped` for this file, it was enough to move same style to reusable component and it would work. Classes in reusable components are renamed, but they match template.
I also tested this page and it is pixel perfect to what they had for Partners Hero.

2024-08-23 12:00 UTC, TamaraZoric commented on src/partners/components/PartnerPage.vue
> +      <p v-for="desc in description" :key="desc" v-html="desc"></p>
I actually just added something to have key here since they did not have it, but I agree with you. It makes more sense to use index.

2024-08-26 12:56 UTC, borna9II commented on .vitepress/theme/components/CardList.vue
> +    ;[array[i], array[j]] = [array[j], array[i]]
@29avet1 please change this one to be as mentioned on 1. bullet if it isn't resolved

2024-08-27 10:53 UTC, 29avet1 commented on .vitepress/theme/components/CardList.vue
> +    ;[array[i], array[j]] = [array[j], array[i]]
I chose the safest option - added a comment to not remove the smicolon :D

2024-08-28 09:05 UTC, merged

2024-08-28 15:32 UTC, borna9II commented on .gitignore
> +.idea
To remove

2024-08-28 15:32 UTC, borna9II commented on src/developers/components/CloudinaryImage.vue
> +  className?: string,
remove commas

2024-08-28 15:32 UTC, borna9II commented on src/developers/components/CloudinaryImage.vue
> +  return `${cloudinaryUrl}/${attributes}/v1/${props.src.replace(/^\/+/, '')}`;
remove commas?

2024-08-28 15:32 UTC, borna9II commented on src/developers/components/CloudinaryImage.vue
Move the file to .vitepress/theme/component folder

2024-08-28 15:32 UTC, borna9II commented on src/developers/components/CloudinaryImage.vue
> +  className?: string,
please review all other places where we have added them

2024-08-28 15:32 UTC, borna9II commented on src/developers/components/DeveloperLanding.vue
> +
2 extra spaces

2024-08-28 15:47 UTC, 29avet1 commented on src/developers/components/CloudinaryImage.vue
I'm not sure if we have to move it to global components, at the moment it is used only for developer images.

2024-08-28 15:51 UTC, 29avet1 commented on .gitignore
> +.idea
I'd like to keep it, as this is a folder made by JetBrains IDE and it is better to always ignore it